USE [WIT]
GO

/****** Object:  Table [dbo].[LItemPropValueText]    Script Date: 11/13/2017 11:09:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[LItemPropValueText](
	[ItemPropValueID] [bigint] NOT NULL,
	[Value] [varchar](max) NOT NULL,
 CONSTRAINT [PK_LItemPropValueText] PRIMARY KEY CLUSTERED 
(
	[ItemPropValueID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[LItemPropValueText]  WITH CHECK ADD  CONSTRAINT [FK_LItemPropValueText_LItemPropValue] FOREIGN KEY([ItemPropValueID])
REFERENCES [dbo].[LItemPropValue] ([ItemPropValueID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[LItemPropValueText] CHECK CONSTRAINT [FK_LItemPropValueText_LItemPropValue]
GO


