USE [WIT]
GO

/****** Object:  Table [dbo].[LItemValueString]    Script Date: 11/13/2017 11:08:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[LItemValueString](
	[ItemValueID] [bigint] NOT NULL,
	[Value] [varchar](1000) NOT NULL,
 CONSTRAINT [PK_LItemValueString] PRIMARY KEY CLUSTERED 
(
	[ItemValueID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[LItemValueString]  WITH CHECK ADD  CONSTRAINT [FK_LItemValueString_LItemValue] FOREIGN KEY([ItemValueID])
REFERENCES [dbo].[LItemValue] ([ItemValueID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[LItemValueString] CHECK CONSTRAINT [FK_LItemValueString_LItemValue]
GO


