USE [WIT]
GO

/****** Object:  Table [dbo].[LItemValueInteger]    Script Date: 11/13/2017 11:10:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[LItemValueInteger](
	[ItemValueID] [bigint] NOT NULL,
	[Value] [int] NOT NULL,
 CONSTRAINT [PK_LItemValueInteger] PRIMARY KEY CLUSTERED 
(
	[ItemValueID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[LItemValueInteger]  WITH CHECK ADD  CONSTRAINT [FK_LItemValueInteger_LItemValue] FOREIGN KEY([ItemValueID])
REFERENCES [dbo].[LItemValue] ([ItemValueID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[LItemValueInteger] CHECK CONSTRAINT [FK_LItemValueInteger_LItemValue]
GO


