USE [WIT]
GO

/****** Object:  Table [dbo].[LItemValueDecimal]    Script Date: 11/13/2017 11:12:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[LItemValueDecimal](
	[ItemValueID] [bigint] NOT NULL,
	[Value] [numeric](30,8) NOT NULL,
 CONSTRAINT [PK_LItemValueDecimal] PRIMARY KEY CLUSTERED 
(
	[ItemValueID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[LItemValueDecimal]  WITH CHECK ADD  CONSTRAINT [FK_LItemValueDecimal_LItemValue] FOREIGN KEY([ItemValueID])
REFERENCES [dbo].[LItemValue] ([ItemValueID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[LItemValueDecimal] CHECK CONSTRAINT [FK_LItemValueDecimal_LItemValue]
GO


