//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LItemPropValue
    {
        public long ItemPropValueID { get; set; }
        public long ItemPropID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual LItemProp LItemProp { get; set; }
        public virtual LItemPropValueDateTime LItemPropValueDateTime { get; set; }
        public virtual LItemPropValueDecimal LItemPropValueDecimal { get; set; }
        public virtual LItemPropValueInteger LItemPropValueInteger { get; set; }
        public virtual LItemPropValueString LItemPropValueString { get; set; }
        public virtual LItemPropValueText LItemPropValueText { get; set; }
    }
}
