//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LItemValueItem
    {
        public long ItemValueID { get; set; }
        public long Value { get; set; }
        public Nullable<int> Nill { get; set; }
    
        public virtual LItem LItem { get; set; }
        public virtual LItemValue LItemValue { get; set; }
    }
}
