//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LItemTypeLookup
    {
        public int ItemTypeID { get; set; }
        public int ItemPropID { get; set; }
        public Nullable<int> Nill { get; set; }
    
        public virtual LItemProp LItemProp { get; set; }
        public virtual LItemType LItemType { get; set; }
    }
}
