//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIT.Data.Models
{
    using System;
    
    public enum LPropTypeEnum : int
    {
        String = 0,
        Integer = 2,
        Decimal = 3,
        Date = 4,
        Time = 5,
        DateTime = 6,
        Text = 1,
        Item = 100,
        Image = 7,
        Video = 8,
        Hyperlink = 9
    }
}
