//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIT.Data.Models
{
    using System;
    
    public enum LValueRule : int
    {
        SingleOptional = 0,
        SingleRequired = 1,
        MultipleOptional = 2,
        MultipleRequired = 3
    }
}
